import {
  BookMarked,
  BookOpen,
  BriefcaseBusiness,
  CalendarCheck,
  Clapperboard,
  CodeXml,
  Dumbbell,
  DraftingCompass,
  Footprints,
  Heart,
  List,
  Map,
  UtensilsCrossed,
} from "lucide-react";

export const CLASS_CATEGORY = [
  { id: 1, label: "전체", category: "", icon: <List /> },
  { id: 2, label: "포트폴리오", category: "portfolio", icon: <BriefcaseBusiness /> },
  { id: 3, label: "일기", category: "diary", icon: <BookOpen /> },
  { id: 4, label: "계획", category: "plan", icon: <CalendarCheck /> },
  { id: 5, label: "자기계발", category: "self-development", icon: <Footprints /> },
  { id: 6, label: "디자인", category: "design", icon: <DraftingCompass /> },
  { id: 7, label: "IT·프로그래밍", category: "programming", icon: <CodeXml /> },
  { id: 8, label: "독후감", category: "book-review", icon: <BookMarked /> },
  { id: 9, label: "여행일지", category: "travel", icon: <Map /> },
  { id: 10, label: "취미", category: "hobby", icon: <Heart /> },
  { id: 11, label: "운동", category: "fitness", icon: <Dumbbell /> },
  { id: 12, label: "영화·드라마", category: "entertainment", icon: <Clapperboard /> },
  { id: 13, label: "음식·맛집", category: "food", icon: <UtensilsCrossed /> },
];

export const TOPIC_CATEGORY = [
  { id: 1, label: "포트폴리오", category: "portfolio" },
  { id: 2, label: "일기", category: "diary" },
  { id: 3, label: "계획", category: "plan" },
  { id: 4, label: "자기계발", category: "self-development" },
  { id: 5, label: "디자인", category: "design" },
  { id: 6, label: "IT·프로그래밍", category: "programming" },
  { id: 7, label: "독후감", category: "book-review" },
  { id: 8, label: "여행일지", category: "travel" },
  { id: 9, label: "취미", category: "hobby" },
  { id: 10, label: "운동", category: "fitness" },
  { id: 11, label: "영화·드라마", category: "entertainment" },
  { id: 12, label: "음식·맛집", category: "food" },
];
